### ISSUE TITLE
Sequences by OTU: "Error: subscript out of bounds."

### ISSUE THREAD

**Issue by fwhelan** [beiko-lab/ananke-ui#2]
This is on following the tutorial and wiki. Seems to be for each OTU cluster number. R output: 

```
Warning: Error in [: subscript out of bounds
Stack trace (innermost first):
    80: plot
    79: matplot
    78: renderPlot [/private/var/folders/8m/ldvgxhps37521sg0bktp0h6m0000gn/T/RtmpMzkHFQ/shinyapp453c41b99fbf/timeclust-ui-master/server.R#270]
    70: output$otu_plot
     3: runApp
     2: runUrl
     1: runGitHub
```

**Comment by mwhall** [comment]
Weird, it's able to get all the way past my code and into the matplot's subcall before it crashes. I'm not sure that Warning is related to the error at hand. That warning pops up occasionally because Shiny jumps the gun and wants to load data before the user has selected a parameter, and it's harmless.

Does the info table at the bottom load properly, or does it completely crash (grey screen rather than some red text) when this error happens?

**Comment by fwhelan** [comment]
I got red text at the top (Error: subscript out of bounds) followed by lots of white space then the bones of a Table at the bottom with "No data available in table".

**Comment by mwhall** [comment]
It sounds like when it's trying to fetch the OTUs, it is getting an empty subset from the time-series table. The OTU number drop-down is populating correctly? I think you would see this error for the "NA" cluster that is the result of UPARSE not being able to match a sequence to a cluster, but not for any of the clusters with proper numerical labels.

**Comment by fwhelan** [comment]
Yes, the OTU number drop-down is populating correctly, as is the PhyloClusterNumber in the Sequences by Time Cluster table (if those match up?)

When I switch between clusters, I can see more clearly which warnings and errors pop up. These seem to all appear every time I try to produce the table:

```
Warning in matrix(x, nrow = n, ncol = ky) :
  data length exceeds size of matrix
Warning in min(x) : no non-missing arguments to min; returning Inf
Warning in max(x) : no non-missing arguments to max; returning -Inf
Warning in min(x) : no non-missing arguments to min; returning Inf
Warning in max(x) : no non-missing arguments to max; returning -Inf
Warning: Error in [: subscript out of bounds
Stack trace (innermost first):
    80: plot
    79: matplot
    78: renderPlot [/private/var/folders/8m/ldvgxhps37521sg0bktp0h6m0000gn/T/RtmpMzkHFQ/shinyapp453c2638b779/timeclust-ui-master/server.R#270]
    70: output$otu_plot
     3: runApp
     2: runUrl
     1: runGitHub
```

**Comment by mwhall** [comment]
I had a bunch of changes that I hadn't pushed that were around that code, as well as a fix for what I think was the cause (converting the OTU numbers to numeric). It's worth re-running with these changes to see if that fixed it.

**Comment by fwhelan** [comment]
That did it! Thanks!
